const mockUserData = {
  name: 'Amy Waller',
  id: 'user-1',
};

// 50 subjects: 40 Individual, 35 Group, 20 Family
// Distribution: 20 with all three, 15 with Individual+Group, 5 with Individual only, 10 with none
const mockSubjects = [
  // 1-20: Individual, Group, Family (20 subjects)
  { id: 'sub-1', name: 'Autumn Phillips', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Individual' },
  { id: 'sub-2', name: 'Daniel Hamilton', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'To do' },
  { id: 'sub-3', name: 'Ricky Smith', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'Absentees' },
  { id: 'sub-4', name: 'Joshua Jones', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Individual' },
  { id: 'sub-5', name: 'Rodger Struck', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'Group' },
  { id: 'sub-6', name: 'Sarah Connor', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Family' },
  { id: 'sub-7', name: 'Emily Watson', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Individual' },
  { id: 'sub-8', name: 'Michael Chen', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'To do' },
  { id: 'sub-9', name: 'Jessica Martinez', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Group' },
  { id: 'sub-10', name: 'David Kim', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'Absentees' },
  { id: 'sub-11', name: 'Amanda Foster', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Family' },
  { id: 'sub-12', name: 'Christopher Lee', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'Individual' },
  { id: 'sub-13', name: 'Nicole Brown', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Group' },
  { id: 'sub-14', name: 'Kevin Patel', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'To do' },
  { id: 'sub-15', name: 'Rachel Green', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Family' },
  { id: 'sub-16', name: 'James Wilson', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'Absentees' },
  { id: 'sub-17', name: 'Lauren Taylor', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Individual' },
  { id: 'sub-18', name: 'Matthew Garcia', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'Group' },
  { id: 'sub-19', name: 'Samantha Anderson', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Active', category: 'Family' },
  { id: 'sub-20', name: 'Andrew Thomas', pictureTypes: ['Individual', 'Group', 'Family'], status: 'Inactive', category: 'To do' },
  // 21-35: Individual, Group (15 subjects)
  { id: 'sub-21', name: 'Stephanie Clark', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'Individual' },
  { id: 'sub-22', name: 'Ryan White', pictureTypes: ['Individual', 'Group'], status: 'Inactive', category: 'Group' },
  { id: 'sub-23', name: 'Melissa Harris', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'Absentees' },
  { id: 'sub-24', name: 'Brandon Martin', pictureTypes: ['Individual', 'Group'], status: 'Inactive', category: 'To do' },
  { id: 'sub-25', name: 'Heather Thompson', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'Individual' },
  { id: 'sub-26', name: 'Jason Moore', pictureTypes: ['Individual', 'Group'], status: 'Inactive', category: 'Group' },
  { id: 'sub-27', name: 'Ashley Jackson', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'Family' },
  { id: 'sub-28', name: 'Eric Lewis', pictureTypes: ['Individual', 'Group'], status: 'Inactive', category: 'Absentees' },
  { id: 'sub-29', name: 'Michelle Walker', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'Individual' },
  { id: 'sub-30', name: 'Timothy Hall', pictureTypes: ['Individual', 'Group'], status: 'Inactive', category: 'To do' },
  { id: 'sub-31', name: 'Christina Allen', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'Group' },
  { id: 'sub-32', name: 'Justin Young', pictureTypes: ['Individual', 'Group'], status: 'Inactive', category: 'Family' },
  { id: 'sub-33', name: 'Elizabeth King', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'Individual' },
  { id: 'sub-34', name: 'Nathan Wright', pictureTypes: ['Individual', 'Group'], status: 'Inactive', category: 'Absentees' },
  { id: 'sub-35', name: 'Rebecca Scott', pictureTypes: ['Individual', 'Group'], status: 'Active', category: 'To do' },
  // 36-40: Individual only (5 subjects)
  { id: 'sub-36', name: 'Benjamin Adams', pictureTypes: ['Individual'], status: 'Inactive', category: 'Individual' },
  { id: 'sub-37', name: 'Katherine Baker', pictureTypes: ['Individual'], status: 'Active', category: 'Group' },
  { id: 'sub-38', name: 'Samuel Nelson', pictureTypes: ['Individual'], status: 'Inactive', category: 'To do' },
  { id: 'sub-39', name: 'Victoria Hill', pictureTypes: ['Individual'], status: 'Active', category: 'Family' },
  { id: 'sub-40', name: 'Jonathan Campbell', pictureTypes: ['Individual'], status: 'Inactive', category: 'Absentees' },
  // 41-50: No photo types (10 subjects)
  { id: 'sub-41', name: 'Olivia Mitchell', pictureTypes: [], status: 'Active', category: 'Individual' },
  { id: 'sub-42', name: 'Alexander Roberts', pictureTypes: [], status: 'Inactive', category: 'To do' },
  { id: 'sub-43', name: 'Hannah Turner', pictureTypes: [], status: 'Inactive', category: 'Absentees' },
  { id: 'sub-44', name: 'Daniel Phillips', pictureTypes: [], status: 'Active', category: 'Group' },
  { id: 'sub-45', name: 'Abigail Evans', pictureTypes: [], status: 'Inactive', category: 'Family' },
  { id: 'sub-46', name: 'William Edwards', pictureTypes: [], status: 'Active', category: 'Individual' },
  { id: 'sub-47', name: 'Sophia Collins', pictureTypes: [], status: 'Inactive', category: 'To do' },
  { id: 'sub-48', name: 'Joseph Stewart', pictureTypes: [], status: 'Active', category: 'Absentees' },
  { id: 'sub-49', name: 'Emma Sanchez', pictureTypes: [], status: 'Inactive', category: 'Group' },
  { id: 'sub-50', name: 'Mason Morris', pictureTypes: [], status: 'Active', category: 'Family' },
];

const mockFilters = [
  { id: 'all', labelKey: 'filterAll' },
  { id: 'toDo', labelKey: 'filterToDo' },
  { id: 'absentees', labelKey: 'filterAbsentees' },
  { id: 'individual', labelKey: 'filterIndividual' },
  { id: 'group', labelKey: 'filterGroup' },
  { id: 'family', labelKey: 'filterFamily' },
];

const mockTaggingModes = {
  single: 'single',
  multi: 'multi',
};

const translations = {
  en: {
    statusBarName: 'M 3284791',
    subjectsTitle: 'Subjects',
    maxCodesToast: 'This camera only accepts a max of 3 codes',
    switchModeModalTitle: 'Names will be deleted',
    switchModeModalText: 'Do not show again',
    switchModeModalCancel: 'Cancel',
    switchModeModalConfirm: 'Continue',
    settingsTitle: 'Settings',
    settingsLanguage: 'Language:',
    settingsBack: 'Back',
    nameListTab: 'Name list',
    scanCodeTab: 'Scan code',
    devicesTab: 'Devices',
    settingsTab: 'Settings',
    filterAll: 'All',
    filterToDo: 'To do',
    filterAbsentees: 'Absentees',
    filterIndividual: 'Individual',
    filterGroup: 'Group',
    filterFamily: 'Family',
    subjectCardNoSubject: 'No subject selected',
    subjectCardClose: 'Close',
    subjectCardGroup: 'Group',
    subjectCardClearAll: 'Clear All',
    modalOk: 'OK',
    edit: 'Edit',
    addCustomer: 'Add Customer',
  },
  de: {
    statusBarName: 'M 3284791',
    subjectsTitle: 'Personen',
    maxCodesToast: 'Diese Kamera akzeptiert maximal 3 Codes',
    switchModeModalTitle: 'Namen werden gelöscht',
    switchModeModalText: 'Nicht erneut anzeigen',
    switchModeModalCancel: 'Abbrechen',
    switchModeModalConfirm: 'Fortfahren',
    settingsTitle: 'Einstellungen',
    settingsLanguage: 'Sprache:',
    settingsBack: 'Zurück',
    nameListTab: 'Namensliste',
    scanCodeTab: 'Code scannen',
    devicesTab: 'Geräte',
    settingsTab: 'Einstellungen',
    filterAll: 'Alle',
    filterToDo: 'Zu erledigen',
    filterAbsentees: 'Abwesende',
    filterIndividual: 'Einzeln',
    filterGroup: 'Gruppe',
    filterFamily: 'Familie',
    subjectCardNoSubject: 'Kein person ausgewählt',
    subjectCardClose: 'Schließen',
    subjectCardGroup: 'Gruppe',
    subjectCardClearAll: 'Alles löschen',
    modalOk: 'OK',
    edit: 'Bearbeiten',
    addCustomer: 'Person hinzufügen',
  },
};

export { mockUserData, mockSubjects, mockFilters, mockTaggingModes, translations };